---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: space-hackability
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: space-hackability
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
    # semver:
    #   range: '>=0.0.0'
