---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: space-hackability
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: space-hackability
  policy:
    semver:
      range: '>=0.0.0'

