---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: hackability-dev
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: hackability-dev
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 0m30s
