---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: space-hackability
  namespace: flux-system
spec:
  image: ghcr.io/hackability-dev/space-hackability/app
  interval: 0m30s
