apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hackability-space
  namespace: hackability-test
spec:
  interval: 5m
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: space-hackability-code
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    image:
      repository: ghcr.io/hackability-dev/space-hackability/app
      tag: 'main-998f4f9-1616855732' # {"$imagepolicy": "flux-system:space-hackability:tag"}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: 'traefik'
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        traefik.ingress.kubernetes.io/redirect-entry-point: https
      hosts:
        - host: space-test.k8s.hackability.dev
          http:
            paths:
              - path: '/'
                pathType: Prefix
                backend:
                  service:
                    name: hackability
                    port:
                      number: 80
      tls:
        - hosts:
            - space-test.k8s.hackability.dev
          secretName: space-test.k8s.hackability.dev-tls
