apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hackability
  name: hackability
  namespace: hackability-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackability
  strategy: {}
  template:
    metadata:
      labels:
        app: hackability
    spec:
      containers:
      - image: ghcr.io/hackability-dev/space-hackability/app:main-cdd5b54-1616860624 # {"$imagepolicy": "flux-system:space-hackability"}
        name: space-hackability
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-postgresql
              key: postgresql-password
        - name: DATABASE_URL
          value: postgresql://postgres:$(POSTGRES_PASSWORD)@db-postgresql:5432/hackability_space?sslmode=disable
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
